NonogramPuzzle/Models/Nonogram.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NonogramPuzzle.Models
{
  public class Nonogram
  {
    public int NonogramId { get; set; }

    [Required(ErrorMessage = "The Nonogram board width is required.")]
    public int NonogramWidth { get; set; }

    [Required(ErrorMessage = "The Nonogram board Height is required.")]
    public int NonogramHeight { get; set; }
    // public List<List<int>> NonogramColClues { get; set; }
    // public List<List<int>> NonogramRowClues { get; set; }

    public int NonogramDim { get; set; } = 0;

    public int solvingBoardWidth { get; set; } = 0;
    public int solvingBoardHeight { get; set; } = 0;
    public int solvingBoardDim { get; set; }  = 0;
    // }
    public List<Cell> Cells { get; set; }
      //this method would run through a nested looping process to determine what the clues are
  }
}

NonogramPuzzle/Controllers/NonogramsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


using NonogramPuzzle.Models;
using NonogramPuzzle.ViewModels;

namespace NonogramPuzzle.Controllers
{
  public class NonogramsController : Controller
  {
    static List<Cell> cellList = new List<Cell>();
    private readonly NonogramPuzzleContext _db;
    
    public NonogramsController(NonogramPuzzleContext db)
    {

      _db = db;
    }

    public ActionResult Index()
    {
      List<Nonogram> model = _db.Nonograms.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Nonogram nonogram)
    {
      if (!ModelState.IsValid)
      {
        return View(nonogram);
      }
      else
      {
        nonogram.NonogramDim = nonogram.NonogramWidth * nonogram.NonogramHeight;
        _db.Nonograms.Add(nonogram);
        _db.SaveChanges();
      }

      return RedirectToAction("Build","CellViewModels");
    }

    public ActionResult Details(int id)
    {
      Nonogram thisNonogram = _db.Nonograms.Include(nono => nono.Cells)
      .FirstOrDefault(nonogram => nonogram.NonogramId == id);

      //calculating dimension for empty board with clues included

      int width = thisNonogram.NonogramWidth;
      int height = thisNonogram.NonogramHeight;
      int boardSize = thisNonogram.NonogramDim;//width * height;//thisNonogram.NonogramDim;
      int maxHeight = 0;
      int maxWidth = 0;

      //calculation board height, accounting for max. number of clues in the columns
      // i = rows/Height, j = columns/width
      for(int j = 0; j < width ; j++)
      {
        int maxColClueCount = 0;

        for(int i = j ; i <= (boardSize - (width - j)); i = (i + width ))
        {
          int previousCell = i;
          if (i >= width)
          {
            previousCell = i - width;
          }
          if (((thisNonogram.Cells.ElementAt(i).CellState == 1) && (i < width)) || ((thisNonogram.Cells.ElementAt(i).CellState == 1) && (thisNonogram.Cells.ElementAt(previousCell).CellState == 0)))
          {
            maxColClueCount ++;
          }
        }
        if( maxHeight < maxColClueCount)
        {
          maxHeight = maxColClueCount;
        }
      }

      //calculation board width, account for max. clues in the rows
      int maxRowClueCount = 0;

      for(int i = 0 ; i < boardSize; i ++)
      {
        if ( i % (width) == 0 && i != 0)
        {
          if(maxWidth < maxRowClueCount)
          {
            maxWidth = maxRowClueCount;
          }

          maxRowClueCount = 0;
        }
        int previousCell = i;
        if (i % width != 0)
        {
          previousCell = i-1;
        }

        if (((thisNonogram.Cells.ElementAt(i).CellState == 1) && (i % width == 0)) || (thisNonogram.Cells.ElementAt(i).CellState == 1) && (thisNonogram.Cells.ElementAt(previousCell).CellState == 0))
          {
            maxRowClueCount++;
          }  
      }

      thisNonogram.solvingBoardWidth = maxWidth + width;
      thisNonogram.solvingBoardHeight = maxHeight + height;
      thisNonogram.solvingBoardDim = (thisNonogram.solvingBoardWidth * thisNonogram.solvingBoardHeight);

      //Saving SolvingBoard Width, Height, and Dim to data base
      _db.Nonograms.Update(thisNonogram);
      _db.SaveChanges();
      
      //clearing the static List object cellList, to preventing additional cells from being add when
      //cell states are being updated and puzzle board refreshes.
      cellList.Clear();
    
      if (cellList.Count < thisNonogram.solvingBoardDim)
      {
        for( int i = 0; i < thisNonogram.solvingBoardDim; i++)
        {
          cellList.Add(new Cell { CellId = i, CellState = 0, NonogramId = id});
        }

        thisNonogram.Cells = cellList;
      }

      for( int j = 0 ; j < maxWidth ; j++)
      {
        int i = j + thisNonogram.solvingBoardWidth;
        thisNonogram.Cells.ElementAt(j).CellState = 1;
        thisNonogram.Cells.ElementAt(i).CellState = 1; 
      }

      //This will not be saved in the database
      return View(thisNonogram);
    }



    public ActionResult Edit(int id)
    {
      Nonogram thisNonogram = _db.Nonograms.FirstOrDefault(nonogram => nonogram.NonogramId == id);
      return View(thisNonogram);
    }

    [HttpPost]
    public ActionResult Edit (Nonogram nonogram)
    {
      _db.Nonograms.Update(nonogram);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Nonogram thisNonogram = _db.Nonograms.FirstOrDefault(nonogram => nonogram.NonogramId == id);
      return View(thisNonogram);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Nonogram thisNonogram = _db.Nonograms.FirstOrDefault(nonogram => nonogram.NonogramId == id);
      _db.Nonograms.Remove(thisNonogram);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public IActionResult HandleCellClickSolve(string id, string cellNumber)
    {
      int cllNmbr = int.Parse(cellNumber);
      int nonoGramId = int.Parse(id);

      Nonogram thisNonogram = _db.Nonograms.FirstOrDefault(nonogram => nonogram.NonogramId == nonoGramId);
      
      Nonogram model = new Nonogram();
      
      cellList.ElementAt(cllNmbr).CellState = (cellList.ElementAt(cllNmbr).CellState +1) % 2;

      model.NonogramId = thisNonogram.NonogramId;
      model.solvingBoardHeight = thisNonogram.solvingBoardHeight;
      model.solvingBoardWidth = thisNonogram.solvingBoardWidth;
      model.solvingBoardDim = thisNonogram.solvingBoardDim;
      model.NonogramWidth = thisNonogram.NonogramWidth;
      model.NonogramHeight = thisNonogram.NonogramHeight;
      model.NonogramDim = thisNonogram.NonogramDim;
      model.Cells = cellList;

      return View("Details", model);
    }
  }
}

NonogramPuzzle/Views/Nonograms/Create.cshtml
@{
    ViewData["Title"] = "Create a new Nonogram Puzzle";
}

@using NonogramPuzzle.Models 
@model NonogramPuzzle.Models.Nonogram

<h2>Create a new Nonogram Puzzle</h2>

<p>@Html.ValidationMessageFor(model => model.NonogramHeight,"",new {@class = "text-danger", @style ="font-weight: 600;"})</p>
<p>@Html.ValidationMessageFor(model => model.NonogramWidth,"", new {@class= "text-danger",@style ="font-weight: 600;"})</p>

  @using (Html.BeginForm("Create","Nonograms","FormMethod.Post"))
  {
      @Html.LabelFor(model => model.NonogramHeight, "Board Height: ")
      @Html.TextBoxFor(model => model.NonogramHeight)

      @Html.LabelFor(model => model.NonogramWidth, "Board Width: ")
      @Html.TextBoxFor(model => Model.NonogramWidth)

      <input type="submit" value="Create" class="btn btn-prmary"/>     
  } 

NonogramPuzzle/Views/Nonograms/Delete.cshtml
@{
    ViewData["Title"] = "Delete Nonogram Puzzle";
}

@model NonogramPuzzle.Models.Nonogram

<h2>Are you sure you want to delete this?</h2>

<h3> NonogramId: @Html.DisplayFor(model => model.NonogramId)</h3>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

NonogramPuzzle/Views/Nonograms/Details.cshtml
@{
    ViewData["Title"] = " Solve Nonogram Puzzle";
}

@model NonogramPuzzle.Models.Nonogram;
@using NonogramPuzzle.Models;
@using System.Collections.Generic;

<h2>Nonogram Details</h2>
<hr />
<h3> Playing Board:  Height- @Html.DisplayFor(model => model.NonogramHeight), Board Width - @Html.DisplayFor(model => model.NonogramWidth), Area: @Html.DisplayFor(model => model.NonogramDim)</h3> 

@{
<h3>Solving Board : Height: @Html.DisplayFor(model => model.solvingBoardHeight), Width - @Html.DisplayFor(model => model.solvingBoardWidth),  Solving Board Area: @Html.DisplayFor(model => model.solvingBoardDim)</h3>

@* add red? *@
    string[] imageNames = {"whitecell.png", "blackcell.png"};
  }


 <form> 
  <div class="cell-zone">
    <input name="id" value="@Model.NonogramId" type="hidden" asp-controller="Nonograms" asp-action= "HandleCellClickSolve" ></input>

    @for (int i = 0; i < @Model.Cells.Count(); i++)
    {
      if (i % @Model.solvingBoardWidth == 0)
      {
        <div class="line-break"></div>
      }

      <div class="puzzleCell">
        <button name="cellNumber" value="@Model.Cells.ElementAt(i).CellId" type="submit" asp-controller="Nonograms" asp-action= "HandleCellClickSolve" >
        <img class="puzzleCellImage" src="~/img/@imageNames[Model.Cells.ElementAt(i).CellState]" />
        <div class="cellLabel">
          @Model.Cells.ElementAt(i).CellId, @Model.Cells.ElementAt(i).NonogramId ;
        </div>
        </button>
      </div> 
    }  
  </div>
</form>

@if (@Model.Cells.Count == 0)
{
  <h3>No cells have been added to this Nonogram yet!</h3>
}
else
{
  <h4>Cells in this Nonogram:</h4>
  <ul>
    @foreach (Cell cell in Model.Cells)
    {
  
          <li>Cell Id: @cell.CellId and Cell State: @cell.CellState</li>  
    }
  </ul>
}

<form>

  <button name="check" value="Check Puzzle" type="submit" asp-controller="Nonograms" asp-action="CheckPuzzle">Check Puzzle</button>
  <br>
  <br>
</form>

<p>@Html.ActionLink("Edit Nonogram", "Edit", new {id = Model.NonogramId})</p>
<p>@Html.ActionLink("Delete Nonogram", "Delete", new { id = @Model.NonogramId})</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

NonogramPuzzle/Views/Nonograms/Edit.cshtml
@model NonogramPuzzle.Models.Nonogram
<div class="container">
  <h2>Edit</h2>

  <h4>Edit this nonogram: @Html.DisplayFor(model => model.NonogramId)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.NonogramId)
    
    @Html.LabelFor(model => model.NonogramWidth)
    @Html.EditorFor(model => model.NonogramWidth)

    @Html.LabelFor(model => model.NonogramHeight)
    @Html.EditorFor(model => model.NonogramHeight)

    <input type="submit" value="Save" />
  }
  <p>@Html.ActionLink("Back to list", "Index")</p>
  @Html.ActionLink("Delete", "Delete")
  

</div>

NonogramPuzzle/Views/Nonograms/Index.cshtml
@{
    ViewData["Title"] = "Nonogram Home Page";
}

@using NonogramPuzzle.Models;
<div class ="container">
  <h1>Nonogram</h1>

  @if (@Model.Count == 0)
  {
    <h3>No Nonograms have been added yet!</h3>
  }

  <ul>
    @foreach(Nonogram nonogram in Model)
    {
      <li>@Html.ActionLink($"Nonogram Id: {nonogram.NonogramId}","Details", new { id = nonogram.NonogramId})</li>
    }
  </ul>

  <p>@Html.ActionLink("Add new nonogram", "Create")</p>
</div>